### ISSUE TITLE
As a potential user, I want to be able to register as a user with my credentials to get access  to the game.

### ISSUE THREAD

**Issue by Chopstew** [sopra-fs23-group-10/sopra-fs23-group-10-server#1]
**Acceptance Criteria (= Development Tasks):**
- [x] sopra-fs23-group-10/sopra-fs23-group-10-client#1
- [x] sopra-fs23-group-10/sopra-fs23-group-10-client#2
- [x] sopra-fs23-group-10/sopra-fs23-group-10-client#3
- [x] sopra-fs23-group-10/sopra-fs23-group-10-server#34
- [x] #77

**Comment by Chopstew** [comment]
All Dev Tasks are completed and acceptance criterias are met. Issue is therefore closed.
