### ISSUE TITLE
As a logged-in user, after selecting a duel game mode, I want to invite another user to a game to play together.

### ISSUE THREAD

**Issue by Chopstew** [sopra-fs23-group-10/sopra-fs23-group-10-server#18]
**Acceptance Criteria:**

- [x] After selecting duel game mode, the user can invite an online user to join a duel game
- [x] The invited user receives a message to decline or accept the invitation
- [x] If the invited user does not accept the invitation in a defined time limit, the invitation is cancelled
- [x] If the invited user accepts the invitation, both players get redirected to the duel game mode

**Development Tasks:**
- [x] sopra-fs23-group-10/sopra-fs23-group-10-client#15
- [x] sopra-fs23-group-10/sopra-fs23-group-10-client#16
- [x] sopra-fs23-group-10/sopra-fs23-group-10-server#74
- [x] #75
- [x] sopra-fs23-group-10/sopra-fs23-group-10-client#17
- [x] sopra-fs23-group-10/sopra-fs23-group-10-client#18

**Comment by Chopstew** [comment]
All dev tasks are completed and acceptance criterias are met. Issue is therefore closed.
