### ISSUE TITLE
As a registered user, I want to log into my account with my credentials to get access to the  game.

### ISSUE THREAD

**Issue by Chopstew** [sopra-fs23-group-10/sopra-fs23-group-10-server#2]
**Acceptance Criteria (= Development Tasks):**
- [x] sopra-fs23-group-10/sopra-fs23-group-10-client#4
- [x] sopra-fs23-group-10/sopra-fs23-group-10-client#5
- [x] sopra-fs23-group-10/sopra-fs23-group-10-client#6
- [x] sopra-fs23-group-10/sopra-fs23-group-10-server#38

**Comment by Chopstew** [comment]
All Dev Tasks are completed and acceptance criterias are met. Issue is therefore closed.
