### ISSUE TITLE
As a player in a match, I want to go through ten questions where we alternate in the selection of question topics, so the game is interactive and fair

### ISSUE THREAD

**Issue by Chopstew** [sopra-fs23-group-10/sopra-fs23-group-10-server#20]
**Acceptance Criteria:**
- [x] In each round a question is displayed with four possible answers
- [x] Players choose their answer within a time limit of 15 seconds
- [x] Players click one of the answers to send off their answer
- [x] A round ends when both players have answered, or the timer has run out

**Development Tasks:**
- [x] sopra-fs23-group-10/sopra-fs23-group-10-client#19
- [x] sopra-fs23-group-10/sopra-fs23-group-10-client#20
- [x] sopra-fs23-group-10/sopra-fs23-group-10-client#21
- [x] sopra-fs23-group-10/sopra-fs23-group-10-server#57
- [x] sopra-fs23-group-10/sopra-fs23-group-10-server#58

**Comment by Chopstew** [comment]
All dev tasks are completed and acceptance criterias are met. Issue is therefore closed.
