### ISSUE TITLE
As a player, I want to see the current scores of both players after each answered question to compare myself with the opponent

### ISSUE THREAD

**Issue by Chopstew** [sopra-fs23-group-10/sopra-fs23-group-10-server#21]
**Acceptance Criteria:**
- [x] The scores contain the usernames, profile pictures and the points achieved in the current game
- [x] The scores are only visible for ten seconds
- [x] The player who gets to select the next topic is shown the topic selection at the same time

**Development Tasks:**
- [x] sopra-fs23-group-10/sopra-fs23-group-10-client#22
- [x] sopra-fs23-group-10/sopra-fs23-group-10-server#60
- [x] sopra-fs23-group-10/sopra-fs23-group-10-client#23
- [x] sopra-fs23-group-10/sopra-fs23-group-10-client#24

**Comment by Chopstew** [comment]
All dev tasks are completed and acceptance criterias are met. Issue is therefore closed.
