### ISSUE TITLE
As a single player, I go through ten questions per game to test my own knowledge.

### ISSUE THREAD

**Issue by Chopstew** [sopra-fs23-group-10/sopra-fs23-group-10-server#22]
**Acceptance Criteria:**
- [x] In each round, a question is displayed with four possible answers
- [x] The player chooses their answer within a time limit of 15 seconds
- [x] The player clicks one of the answers to send off their answer
- [x] A round ends when the player has answered, or the timer has run out

**Dev Tasks:**
- [x] sopra-fs23-group-10/sopra-fs23-group-10-client#36
- [x] sopra-fs23-group-10/sopra-fs23-group-10-client#37
- [x] sopra-fs23-group-10/sopra-fs23-group-10-client#38
- [x] sopra-fs23-group-10/sopra-fs23-group-10-client#39
- [x] sopra-fs23-group-10/sopra-fs23-group-10-server#94

**Comment by Chopstew** [comment]
All dev tasks are completed and acceptance criterias are met (with the time limit changed to 30 seconds to improve user experience). Issue is therefore closed.
