### ISSUE TITLE
As a playing user, I want to see my current score after each answered question in order to keep track of the game status. 

### ISSUE THREAD

**Issue by Chopstew** [sopra-fs23-group-10/sopra-fs23-group-10-server#23]
**Acceptance Criteria:**
- [x] The scores are only visible for ten seconds
- [x] The user can see how many questions they already answered and how many of them were correct

**Dev Tasks:**
- [x] sopra-fs23-group-10/sopra-fs23-group-10-client#40
- [x] sopra-fs23-group-10/sopra-fs23-group-10-client#41
- [x] sopra-fs23-group-10/sopra-fs23-group-10-server#98
- [x] #115

**Comment by Chopstew** [comment]
All dev tasks are completed and acceptance criterias are met. Issue is therefore closed.
