### ISSUE TITLE
As a player, I get points according to my performance so I can compare myself

### ISSUE THREAD

**Issue by Chopstew** [sopra-fs23-group-10/sopra-fs23-group-10-server#24]
**Acceptance Criteria:**
- [x] If a player does not answer before the countdown runs out or chooses the wrong answer, they get 0 points
- [x] The performance of a user is measured by correctness of the answer and response speed
- [x] The points are accumulated over all games and stored permanently

**Development Tasks:**
- [x] sopra-fs23-group-10/sopra-fs23-group-10-client#25
- [x] sopra-fs23-group-10/sopra-fs23-group-10-server#64
- [x] sopra-fs23-group-10/sopra-fs23-group-10-server#65
- [x] sopra-fs23-group-10/sopra-fs23-group-10-server#66

**Comment by Chopstew** [comment]
All dev tasks are completed and acceptance criterias are met. Issue is therefore closed.
