### ISSUE TITLE
As a player whose turn it is, I want to select the next topic from a range of three topics in  order to increase my chance of winning.

### ISSUE THREAD

**Issue by Chopstew** [sopra-fs23-group-10/sopra-fs23-group-10-server#26]
**Acceptance Criteria:**
- [x] The selecting user can choose from three general topics (e.g., geography, sports, movies)
- [x] The topics to choose from are randomly selected from a variety of available topics
- [x] The turn to select the topic is evenly distributed between both players
- [x] The challenged player gets to choose the topic first at the beginning of a match

**Development Tasks:**
- [x] sopra-fs23-group-10/sopra-fs23-group-10-client#26
- [x] sopra-fs23-group-10/sopra-fs23-group-10-server#68
- [x] sopra-fs23-group-10/sopra-fs23-group-10-server#69
- [x] sopra-fs23-group-10/sopra-fs23-group-10-server#70
- [x] sopra-fs23-group-10/sopra-fs23-group-10-server#71

**Comment by Chopstew** [comment]
All dev tasks are completed and acceptance criterias are met. Issue is therefore closed.
