### ISSUE TITLE
As a player, I want to test my knowledge on a specific topic by selecting one of all available topics in order to test and deepen my knowledge

### ISSUE THREAD

**Issue by Chopstew** [sopra-fs23-group-10/sopra-fs23-group-10-server#27]
**Acceptance Criteria:**
- [x] The topics to choose from are all available topics
- [x] The selection is shown before a new single player game starts
- [x] All following questions are of the chosen topic

**Dev Tasks:**
- [x] sopra-fs23-group-10/sopra-fs23-group-10-client#43
- [x] sopra-fs23-group-10/sopra-fs23-group-10-client#44
- [x] sopra-fs23-group-10/sopra-fs23-group-10-client#45
- [x] sopra-fs23-group-10/sopra-fs23-group-10-server#105
- [x] #113

**Comment by Chopstew** [comment]
All dev tasks are completed and acceptance criterias are met. Issue is therefore closed.
