### ISSUE TITLE
As a user, I want to reset my lost password via email if I have forgotten it to regain access  to my account

### ISSUE THREAD

**Issue by Chopstew** [sopra-fs23-group-10/sopra-fs23-group-10-server#4]
**Acceptance Criteria:**
- [x] Upon success, the user receives an email with a link to reset his password
- [x] Upon success, the user gets redirected to the login in which they can log with his newly set password
- [x] Upon failure, an error is displayed, and the user is redirected to the login screen

**Dev Tasks:**
- [x] sopra-fs23-group-10/sopra-fs23-group-10-client#50
- [x] sopra-fs23-group-10/sopra-fs23-group-10-server#119
- [x] sopra-fs23-group-10/sopra-fs23-group-10-server#120

**Comment by Chopstew** [comment]
All dev tasks are completed and acceptance criterias are met or similarly implemented in acceptable fashion. Issue is therefore closed.
