### ISSUE TITLE
As a user, I want to be able to log out of my account to leave the web application

### ISSUE THREAD

**Issue by Chopstew** [sopra-fs23-group-10/sopra-fs23-group-10-server#5]
**Acceptance Criteria:**
- [ ] Upon successful logout the user sees the login screen

**Development Tasks:**
- [x] sopra-fs23-group-10/sopra-fs23-group-10-client#7
- [x] sopra-fs23-group-10/sopra-fs23-group-10-server#40
- [x] sopra-fs23-group-10/sopra-fs23-group-10-client#28

**Comment by Chopstew** [comment]
All dev tasks are completed and acceptance criterias are met. Issue is therefore closed.
